# Generated by Django 2.1.7 on 2019-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shopping_list', models.CharField(max_length=100000)),
                ('ingredients', models.CharField(max_length=100000)),
                ('instructions', models.CharField(max_length=100000)),
                ('prep_time', models.CharField(max_length=10)),
                ('cook_time', models.CharField(max_length=10)),
                ('total_time', models.CharField(max_length=10)),
                ('servings', models.CharField(max_length=30)),
            ],
        ),
    ]
